lms_dashboard/authentication/urls.py
# authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import CustomLoginView, LogoutView

app_name = 'authentication'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

lms_dashboard/dashboard/urls.py
# dashboard_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import dashboard, get_data,about


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='dashboard'),
    path('get_data/', get_data, name='get_data'),
    path('about/', about, name='about'),
]

lms_dashboard/lms_dashboard/urls.py
# lms_dashboard/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('auth/', include('authentication.urls')),
]

lms_dashboard/authentication/models.py
from django.db import models

# Create your models here.

lms_dashboard/dashboard/models.py
# dashboard_app/models.py
from django.db import models

class DataPoint(models.Model):
    label = models.CharField(max_length=255)
    value = models.FloatField()

    def __str__(self):
        return self.label

class DataPoint2(models.Model):
    label = models.CharField(max_length=255)
    value = models.FloatField()

    def __str__(self):
        return self.label

class DataPoint3(models.Model):
    label = models.CharField(max_length=255)
    value = models.FloatField()

    def __str__(self):
        return self.label

lms_dashboard/authentication/views.py
# authentication/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from django.shortcuts import redirect
from django.contrib.auth import logout


class CustomLoginView(LoginView):
    template_name = 'authentication/login.html'

    def get_success_url(self):
        # Redirect to the dashboard page on successful login
        return reverse_lazy('dashboard')

    def form_valid(self, form):
        response = super().form_valid(form)
        # Customize any additional actions you want to perform upon successful login
        # For example, you might want to log some information
        # logger.info(f"User '{self.request.user}' logged in.")
        return response

    def form_invalid(self, form):
        response = super().form_invalid(form)
        # Customize any additional actions you want to perform upon failed login
        # For example, you might want to log some information
        # logger.warning(f"Failed login attempt for user '{form.cleaned_data.get('username')}'.")
        return response

    def get(self, request, *args, **kwargs):
        # If the user is already authenticated, redirect them to the success URL
        if self.request.user.is_authenticated:
            return redirect(self.get_success_url())
        return super().get(request, *args, **kwargs)

class LogoutView(RedirectView):
    # Note: reverse_lazy should not be called here
    # Instead, override the get_redirect_url method

    def get_redirect_url(self, *args, **kwargs):
        # Reverse the URL here
        return reverse_lazy('authentication:login')

    def get(self, request, *args, **kwargs):
        # Logout the user
        logout(request)
        # Call the parent class method
        return super().get(request, *args, **kwargs)

lms_dashboard/dashboard/views.py
# dashboard_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import DataPoint, DataPoint2, DataPoint3

def dashboard(request):
    data_points = DataPoint.objects.all()
    data_points2 = DataPoint2.objects.all()  # Updated variable name
    data_points3 = DataPoint3.objects.all()  # Updated variable name
    labels = [point.label for point in data_points]
    values = [point.value for point in data_points]

    context = {
        'labels': labels,
        'values': values,
        'labels2': [point.label for point in data_points2],  # Add labels for DataPoint2
        'values2': [point.value for point in data_points2],  # Add values for DataPoint2
        'labels3': [point.label for point in data_points3],  # Add labels for DataPoint3
        'values3': [point.value for point in data_points3],  # Add values for DataPoint3
    }

    return render(request, 'dashboard/dashboard.html', context)

def get_data(request):
    data_points = DataPoint.objects.all()
    data = {'labels': [point.label for point in data_points], 'values': [point.value for point in data_points]}
    return JsonResponse(data)

def get_data2(request):
    data_points = DataPoint2.objects.all()
    data = {'labels': [point.label for point in data_points], 'values': [point.value for point in data_points]}
    return JsonResponse(data)

def get_data3(request):
    data_points = DataPoint3.objects.all()
    data = {'labels': [point.label for point in data_points], 'values': [point.value for point in data_points]}
    return JsonResponse(data)

def about(request):
    return render(request, 'dashboard/about.html')

lms_dashboard/authentication/templates/autentication/login.html
<!-- authentication/templates/authentication/login.html -->
{% extends 'dashboard/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <div style="background-color: #fff; padding: 20px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
    <h1>Login</h1>
    <form method="post" action="{% url 'authentication:login' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Login</button>
    </form>
  </div>
{% endblock %}

lms_dashboard/dashboard/templates/comment/base_officer.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block title %}{% endblock %}
    <title>MA</title>



     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />
<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

<link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">



<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">    
<link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">



 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />
<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

<link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

<script src="{% static 'vendor/chart.js/Chart.js' %}"></script>
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>



<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">    
<link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    {% block stylesheet %}{% endblock %}
</head>

<body id="page-top" style="background-color:">

<!-- headers-->
<nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <a class="navbar-brand mr-1 text-primary" href="#">
        <img src="{% static "comment/images/logo.png" %}"  height="70" alt="MotechApp">
      </a>
    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Navbar Search -->
<form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="" method="GET">
        <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </form>

        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-envelope fa-fw"></i>
                <span class="badge badge-danger">{{ pending }}</span>
            </a>
        </li>
           
         <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-bell fa-fw"></i>
                <span class="badge badge-danger"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                <a class="dropdown-item" href="">New Request</a>
            </div>
        </li>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-user-circle fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <a class="dropdown-item" href=""></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="" data-toggle="modal" data-target="#logoutModal">Logout</a>
            </div>
        </li>
    </ul>




</nav>

<div id="wrapper" style="padding-top: 13px;">
<!-- Sidebar -->
<ul class="sidebar navbar-nav" style="padding-top: 90px; height: 100%; width: 700px">


  <li class="nav-item active">
        <a class="nav-link" href="">
            <i class="fa fa-home" aria-hidden="true"></i>
            <span>Admin Dashboard</span>
        </a>
    </li>
      <li class="nav-item">
        <a class="nav-link" href="">
            <i class="fa fa-get-pocket" aria-hidden="true"></i>
            <span style="color: white">Add Post</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="">
            <i class="fa fa-users"></i>
            <span style="color: white">User Profile</span>
        </a>
    </li>

<li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="">
            <i class="fa fa-laptop" aria-hidden="true"></i>
            <span style="color: white">References</span>
        </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown" style="width: 210px">

                    <a class="dropdown-item" href="" class="btn btn-outline-primary">Information</a>
                <div class="dropdown-divider"></div>
<a class="dropdown-item" href="" class="btn btn-outline-primary">Terms</a>
            </div>
        </li>
</ul> 


{% block body %}{% endblock %}
{% block content %}{% endblock content %}


</div>
<!-- /#wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fa fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-danger" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body text-primary"><strong><span>Are You Sure You Want To Log-off ?. Select "Logout" below</span></strong></div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
               <a class="btn btn-primary" href="/logout">Logout</a>
            </div>
        </div>
    </div>
</div>



<script src="{% static 'vendor/chart.js/Chart.js' %}"></script>
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>




<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Page level plugin JavaScript-->
<script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>

<!-- Demo scripts for this page-->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin.min.js' %}"></script>

<script>
    $(".alert-success").fadeTo(2000, 500).slideUp(500, function(){
        $(".alert-success").slideUp(500);
    });
    $(".alert-error").fadeTo(2000, 500).slideUp(500, function(){
        $(".alert-error").slideUp(500);
    });
</script>

{% block javascript %}{% endblock %}

lms_dashboard/dashboard/templates/comment/officer_home.html
{% extends 'comment/base_officer.html' %}
{% load static %}

{% block body %}
 <div id="content-wrapper" style="padding-top: 105px">

        <div class="container-fluid">

            <!-- Breadcrumbs-->
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="">Dashboard</a>
                </li>
                <li class="breadcrumb-item active">Overview</li>
            </ol>

            <!-- Icon Cards-->
            <div class="row">

         <div class="col-sm-6">    
        <canvas id="myChart1" width="300" height="200"></canvas>
                <div>

<script type="text/javascript">
    var ctx = document.getElementById('myChart1').getContext('2d');
    var myChart1 = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: [{% for gender in gender_list %} '{{ gender }}', {% endfor %}],
            datasets: [{
                label:'Gender',
                data: [{% for number in gender_number %} '{{ number }}', {% endfor %}],
                backgroundColor:[
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 135, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(151, 102, 132, 1)',
                'rgba(153, 99, 132, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 135, 1)',
                'rgba(25, 206, 86, 1)',
                'rgba(211, 192, 192, 1)',
                'rgba(234, 102, 132, 1)',
                'rgba(153, 99, 132, 1)',
                'rgba(255, 159, 64, 1)',
                'gree',
                'yellow',
                ],

                borderColor: [
                'rgba(54, 162, 135, 1)',
                'rgba(25, 206, 86, 1)',
                'rgba(211, 192, 192, 1)',
                'rgba(234, 102, 132, 1)',
                'rgba(153, 99, 132, 1)',
                'rgba(255, 159, 64, 1)',

                ],

                borderWidth: 1
            }]
        },

        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    })
</script>        
</div>
</div>



<div class="col-sm-6">    
<canvas id="myChart" width="300" height="200"></canvas>
                <div>

<script type="text/javascript">
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [{% for course in course_list %} '{{ course }}', {% endfor %}],
            datasets: [{
                label:'Student',
                data: [{% for number in number_list %} '{{ number }}', {% endfor %}],
                backgroundColor:[
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 135, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(151, 102, 132, 1)',
                'rgba(153, 99, 132, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 135, 1)',
                'rgba(25, 206, 86, 1)',
                'rgba(211, 192, 192, 1)',
                'rgba(234, 102, 132, 1)',
                'rgba(153, 99, 132, 1)',
                'rgba(255, 159, 64, 1)',
                'gree',
                'yellow',
                ],

                borderColor: [
                'rgba(54, 162, 135, 1)',
                'rgba(25, 206, 86, 1)',
                'rgba(211, 192, 192, 1)',
                'rgba(234, 102, 132, 1)',
                'rgba(153, 99, 132, 1)',
                'rgba(255, 159, 64, 1)',

                ],

                borderWidth: 1
            }]
        },

        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    })
</script>        
</div>
</div> 


</div>

<br>
<br>
<br>


<!-- end of static icon -->           
        </div>
        </div>
        </div>

{% endblock %}

lms_dashboard/dashboard/templates/dashboard/about.html
<!-- dashboard_app/templates/about.html -->
{% extends 'dashboard/base.html' %}

{% block title %}About Us{% endblock %}

{% block content %}
  <div style="background-color: #fff; padding: 20px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
    <h1 style="color: #333;">About Us</h1>
    <p style="font-size: 16px;">Welcome to our Django Dashboard! We are passionate about creating insightful data visualizations and providing a user-friendly experience.</p>

    <h2 style="color: #555; margin-top: 20px;">Our Mission</h2>
    <p style="font-size: 16px;">To empower users with meaningful data that drives informed decision-making.</p>

    <h2 style="color: #777; margin-top: 20px;">Our Team</h2>
    <p style="font-size: 16px;">We have a dedicated team of developers and designers working together to deliver high-quality dashboards that meet your needs.</p>
  </div>
{% endblock %}

lms_dashboard/dashboard/templates/dashboard/base.html
<!-- dashboard_app/templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django Dashboard{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    integrity="sha512-TsZ0HJ5un8EftmqUcR2RbC5apQxYo1P0ZcxNiiwOJOPTeD7NdmAuRbPw+8RIq7AH9eJhavZRMydrbI9zCuPR4w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            
        }

        header {
            background-color: #004080;
            color: #fff;
            padding: 1em;
            text-align: center;
            
        }

        .sidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color:#004080;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

        .sidenav a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 18px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        .sidenav a:hover {
            color: #f1f1f1;
        }

        .sidenav .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        nav ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        nav ul li {
            display: block;
            margin-bottom: 10px;
        }

        nav ul li a {
            color: #fff;
            text-decoration: none;
            display: block;
            padding: 10px;
        }

        main {
            padding: 20px;
            flex: 1;
        }

        #toggleBtn {
            font-size: 20px;
            cursor: pointer;
        }
        #mode-toggle {
            cursor: pointer;
            font-size: 24px; /* Adjust the size as needed */
            margin-bottom: 16px;
        }

        /* Style for dark mode */
        body.dark-mode {
            background-color: #333;
            color: #fff;
        }

        /* Additional styles for dark mode can be added here */
        body.dark-mode form h2{
            color: #fff; /* Change text color to white in dark mode */
        }
        body.dark-mode form label{
            color: #fff; /* Change text color to white in dark mode */
        }
        
        body.dark-mode form input{
            color: #080000; /* Change text color to white in dark mode */
            background-color: #c9c7c7;
        }
        body.dark-mode p{
            color: #080000; /* Change text color to white in dark mode */
            {% comment %} background-color: #c9c7c7; {% endcomment %}
        }
    </style>
</head>
<body>
    <div>
        <header>
            <h1>Django Dashboard</h1>
            <div style="display:flex;justify-content:space-between;">
                <div style="text-align:left;" id="toggleBtn" onclick="toggleNav()">&#9776;</div>
                <div id="mode-toggle" onclick="toggleMode()">🌙</div>
            </div>
            
        </header>
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <ul>
                <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'authentication:logout' %}">Logout</a></li>
                {% endif %}
                <!-- Add more navigation links as needed -->
                
            </ul>
        </div>
        <main>
            {% block content %}{% endblock %}
        </main>
    </div>

    <script>
        function toggleNav() {
            document.getElementById("mySidenav").style.width = "250px";
        }

        function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
        }
    </script>
    <script>
        // Check if dark mode preference is stored in localStorage
        const isDarkMode = localStorage.getItem('darkMode') === 'true';

        // Set initial dark mode state
        document.body.classList.toggle('dark-mode', isDarkMode);

        function toggleAccountDropdown() {
            var accountOptions = document.getElementById('account-options');
            accountOptions.classList.toggle('show');
        }

        function toggleMode() {
            // Toggle dark mode class on the body
            document.body.classList.toggle('dark-mode');

            // Store the dark mode preference in localStorage
            localStorage.setItem('darkMode', document.body.classList.contains('dark-mode'));

            // Change the toggle icon based on the current mode
            const modeToggle = document.getElementById('mode-toggle');
            const icon = document.body.classList.contains('dark-mode') ? '☀️' : '🌙';
            modeToggle.textContent = icon;

            // Close the account options dropdown when switching modes
            var accountOptions = document.getElementById('account-options');
            accountOptions.classList.remove('show');
        }

        // Close the account options dropdown if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.account-dropdown') && !event.target.matches('.nav-link')) {
                var accountOptions = document.getElementById('account-options');
                accountOptions.classList.remove('show');
            }
        };
    </script>
</body>
</html>